---
- name: this playbook is to set the webserver
  hosts: all

  tasks: 
    - name: wow webserver
      dnf:
        name: "{{ item }"
        state: latest
      loop:
        - httpd
        - firewalld

    - name: check service status
      systemd:
        name: httpd
        state: started
        enabled: no

    - name: check service state
      systemd:
        name: firewalld
        state: stopped
        enabled: no
